proxy:
  image: cr.yandex/crpk1ln2o51l4tvcp5gh/avaproxy:1.1 
  links:
    - generator
  ports:
    - "80:80"
  environment:
      - VM_ADDR=10.0.4.16
      - CONTAINER=http://generator:5000

generator:
  image: genavatar:testing170921
  environment:
    ENV: DEV
  links:
   - monsterpic

monsterpic:
  image: amouat/dnmonster:1.0
