proxy:
  image: cr.yandex/crpk1ln2o51l4tvcp5gh/avaproxy:1.0
  links:
    - generator
  ports:
    - "80:80"
  environment:
      - VM_ADDR=10.128.0.12
      - CONTAINER=http://generator:5000
generator:
  image: cr.yandex/crpk1ln2o51l4tvcp5gh/genavatar:testing020521_2335
  environment:
    ENV: DEV
  links:
   - monsterpic

monsterpic:
  image: amouat/dnmonster:1.0

logspout:
  image: amouat/logspout-logstash
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "8000:80"
  links:
    - logstash
  command: logstash://logstash:5000

logstash:
  image: logstash:1.5
  volumes:
    - /home/$VM_USER/docker-volume/logstash/:/etc/logstash/conf.d/
  environment:
    LOGSPOUT: ignore
  command: -f /etc/logstash/conf.d/ruby-out.conf
