proxy:
  image: avaproxy:testing030521
  links:
    - generator
  ports:
    - "80:80"
generator:
  image: cr.yandex/crpk1ln2o51l4tvcp5gh/genavatar:testing020521_2335
  environment:
    ENV: DEV
  links:
   - monsterpic

monsterpic:
  image: amouat/dnmonster:1.0
